products_url1 = 'https://moveekbuddyshop.com/collections/t-shirts'
products_url2 = 'https://moveekbuddyshop.com/collections/hoodies'
products_url3 = 'https://moveekbuddyshop.com/collections/zip-up-hoodies'
products_url4 = 'https://bestfunnystore.com/collections/leggings'
products_url5 = 'https://gearalover.com/women-leggings'
